### ISSUE TITLE
Extend test cases

### ISSUE THREAD

**Issue by kefahi** [edraj/dmart#240]
During the process of fixing issues that resulted from pydantic2 and redis protocol=3 switch, a number of problems were found that were not covered by the automated tests (curl.sh or pytest).

- Commit  https://github.com/edraj/dmart/commit/c65776de37fb0a219a49b6c3eefdcfa1c7c85970
- utils/access_control.py:38 and schema_migration.py:55 is_file was not called as a function
- Aggregation search

**Comment by saadadel** [comment]
Our current tests cover 40 different APIs and use cases, from user management, resource management, and attachment management to all the different types of queries.

A future plan is to cover Ticket management and add unit tests for the following:
 - Exporter script
 - health check script
 - Notification (mail, SMS, firebase)
 - LDAP

**Comment by saadadel** [comment]
This ticket will be closed since we covered all the missing points.
We also have a future plan to cover the other rarely used scripts.
