### ISSUE TITLE
 Improve Query API to Reject Unused/Unrecognized Fields

### ISSUE THREAD

**Issue by RaniaAbualnadi** [edraj/dmart#350]
Error Handling: Implement error handling mechanisms within the Query API to detect unused or unrecognized fields in queries.

    Error Reporting: Provide informative error messages to users indicating that the queried fields are not supported or recognized.

    Prevent Inaccurate Results: Reject queries with unsupported fields to prevent inaccurate or unexpected search results.

**Comment by saadadel** [comment]
Hello @RaniaAbualnadi 
Thank you for reporting

This [PR](https://github.com/edraj/dmart/pull/349) disallows extra fields in the query API, and it returns informative error message
