### ISSUE TITLE
Implement API Channels Features/ entry updates transactional.

### ISSUE THREAD

**Issue by RaniaAbualnadi** [edraj/dmart#393]
* Consider Api channels features : All and every api call should belong to a pre-defiend channel (e..g mobile, web, chat-bot, ...etc). Each channel comes with a list of api patterns (regex /user/.* , /managed/xxx ) + verb and api Key. The implementation needs to be done on the fastapi middleware level. 
* Consider making entry updates transactional.

**Comment by kefahi** [comment]
This is resolved and merged
