### ISSUE TITLE
Query and Retrieval

### ISSUE THREAD

**Issue by RaniaAbualnadi** [edraj/dmart#433]
Implement functions related to querying and retrieving data from the database.

1.  Implement manticore_db:search.
2.  Implement manticore_repo:search.
3.  Implement manticore_db:aggregate.
4.  Implement manticore_repo:aggregate.
5.  Implement manticore_repo:tags_query.
6.  Implement manticore_repo:random_query.
7.   Implement manticore_db:dto_doc_id.
8.   Implement manticore_db:find.
9.   Implement manticore_db:find_or_fail.
10. Implement manticore_db:find_key.
11.  Implement manticore_db:find_by_id.
12.  Implement manticore_db:find_payload_data_by_id.
13.  Implement manticore_repo:find.
14. Implement manticore_repo:db_doc_to_record.

**Comment by splimter** [comment]
not needed: **dto_doc_id** **find_key** 
not found: **db_doc_to_record**

**Comment by splimter** [comment]
Initial implementation:
- search
- aggregate
- free_search
- find_by_id

**Comment by splimter** [comment]
Done: 
- search
- aggregate
- get_count
- free_search
- dto_doc_id
- find

To be done:
- find_payload_data_by_id
- list_by_ids

**Comment by splimter** [comment]
Query
manticore_db: search :white_check_mark:
manticore_repo: search 
manticore_db: aggregate :white_check_mark:
manticore_repo: aggregate 
manticore_repo: tags_query
manticore_repo: random_query
Alteration
manticore_repo: update
manticore_db: move

Retrieval
manticore_db: dto_doc_id :white_check_mark:
manticore_db: find :white_check_mark:
manticore_db: find_or_fail 
manticore_db: find_key :white_check_mark:
manticore_db: find_by_id :white_check_mark:
manticore_db: find_payload_data_by_id
manticore_repo: find :white_check_mark:
manticore_repo: db_doc_to_record

**Comment by saadadel** [comment]
Query

✅ manticore_db: search
manticore_repo: search
✅ manticore_db: aggregate
manticore_repo: aggregate
manticore_repo: tags_query
manticore_repo: random_query
✅ Alteration
manticore_repo: update
manticore_db: move
Retrieval

✅ manticore_db: dto_doc_id
✅ manticore_db: find
manticore_db: find_or_fail
✅ manticore_db: find_key
✅ manticore_db: find_by_id
manticore_db: find_payload_data_by_id
manticore_repo: find
manticore_repo: db_doc_to_record
