### ISSUE TITLE
Installation  ==> # Build the container      " podman build -t dmart -f Dockerfile" 

### ISSUE THREAD

**Issue by Alibinissa** [edraj/dmart#454]
When you run the # Build the container
"podman build -t dmart -f Dockerfile"
it shows the attached Error!
![Screenshot from 2024-05-12 14-54-24](https://github.com/edraj/dmart/assets/123191147/dc6d3c60-2036-4426-95d4-f9bf2f3f9f50)

**Comment by kefahi** [comment]
Fully resolved
