### ISSUE TITLE
Run the Dmart - # Run the container After adding " work around" 

### ISSUE THREAD

**Issue by Alibinissa** [edraj/dmart#455]
after adding work around 
(replace npm install -> npm install -g yarn && yarn && yarn build PS: there is one npm install" in the Dmart - Docker file
it helps to install the Dmart - docker file 
but once I restart my laptop and try to run the container again the attached Error! appears 

![Screenshot from 2024-05-21 12-50-44](https://github.com/edraj/dmart/assets/123191147/560c0e2f-bea7-42b4-8422-d862d13eb5d3)

Temporary solution: but once the laptop turned off every thing disappear and all date removed so I need to  rebuild and then run it again so the take around 500MB of data each time .

**Comment by kefahi** [comment]
I believe the issues should be now resolved after the many improvements that were introduced.
